/* jshint esversion:8 */
export const unit = {
  temperature: "C",
  residual_capacity: "kW",
  battery_voltage: "V",
  battery_voltage_negative: "V",
  load_ratio: "Hz",
  output_frequency: "V",
  input_voltage_l1: "V",
  input_voltage_l2: "V",
  input_voltage_l3: "V",
  output_voltage_l1: "V",
  output_voltage_l2: "V",
  output_voltage_l3: "V",
  //ac
  refrigeration_temperature: "C",
  refrigeration_stop_deviation: "C",
  evaporation_start_temperature: "C",
  air_change_time: "Min",
  opening_delay: "Min",
  high_temperature_alarm_point: "C",
  return_air_temperature: "C",
  coil_temperature: "C",
  modified_return_air_temperature: "C",
  Correct_air_outlet_temperature: "C",
  defrosting_temperature_setting: "C",
  heating_opening_deviation: "C",
  heating_stop_deviation: "C",
  refrigeration_start_deviation: "C",
  air_outlet_temperature_deviation: "C",
  Starting_temperature_setting: "C",
  temperature_difference: "C",
  air_supply_temperature: "C",
  //power
  active_power: "kW",
  reactive_power: "kW",
  power_factor: "",
  quantity: "W",
  input_voltage: "V",
  input_current: "V",
  input_current_l1: "A",
  input_current_l2: "A",
  input_current_l3: "A",
  input_frequency: "Hz",
  input_frequency_l1: "Hz",
  input_frequency_l2: "Hz",
  input_frequency_l3: "Hz",
  //th
  humidity: "%rh"
};
